from environs import Env

env = Env()
env.read_env()

PAYME_ID = env.str("PAYME_ID")
PAYME_KEY = env.str("PAYME_KEY")

CLICK_SERVICE_ID = env.str("CLICK_SERVICE_ID")
CLICK_MERCHANT_ID = env.str("CLICK_MERCHANT_ID")
CLICK_MERCHANT_USER_ID = env.str("CLICK_MERCHANT_USER_ID")
CLICK_SECRET_KEY = env.str("CLICK_SECRET_KEY")

ATMOS_CONSUMER_KEY = env.str("ATMOS_CONSUMER_KEY")
ATMOS_CONSUMER_SECRET = env.str("ATMOS_CONSUMER_SECRET")
ATMOS_STORE_ID = env.str("ATMOS_STORE_ID")
ATMOS_TERMINAL_ID = env.str("ATMOS_TERMINAL_ID")
ATMOS_API_KEY = env.str("ATMOS_API_KEY")

IS_TEST_MODE = env.bool("IS_TEST_MODE", True)
PAYTECH_LICENSE_API_KEY = env.str("PAYTECH_LICENSE_API_KEY", "your_license_key")

